name: flutter_ca
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  connectivity_plus: ^6.1.4
  d_method: ^0.2.6
  dartz: ^0.10.1
  equatable: ^2.0.7
  extended_image: ^10.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  photo_view: ^0.15.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
